---
title: "Stretch"
author: "Xiyu Zhang"
date: "4/30/2022"
output: html_document
---

```{r packages, message=FALSE, warning=FALSE}
library(tidyverse) 
library(tidytext) 
library(gutenbergr) 
library(SnowballC)
library(topicmodels)
library(igraph)
library(ggraph)
library(tidymodels) 
library(textrecipes) 
library(vip)
library(stopwords)
library(janitor)
library(patchwork)
library(factoextra)
library(gganimate)
library(stats)
library(gifski)
```

##Part 1

```{r stretch-1-1}
vote <- read_csv("votes_time_series.csv")
stretch_fun <- function(x){
  #filter the votes data
  sess <- vote %>%
    replace(., is.na(.), 0) %>%
    filter(session == x) %>%
    select(starts_with("v"))
  
  #run PCA
  sess_pca <- prcomp(sess) %>%
    .$x %>%
    as_tibble() %>%
    select("PC1", "PC2")
  
  sess_combine_1 <- bind_cols(sess, sess_pca)
  
  #conduct kmeans cluster analysis
  sess_clus <- kmeans(sess, centers = 4, nstart = 100)
  sess_combine_2 <- bind_cols(sess_combine_1, cluster = sess_clus$cluster)
  
  return(sess_combine_2)
}
```

```{r stretch 1-4}
set.seed(20220413)
map_votes <- map_df(103:114, stretch_fun) 
map_votes
```

##Part 2

```{r stretch 2-1}
vote_original <- vote %>%
  mutate_all(funs(ifelse(is.na(.), 0, .)))
vote_pc <- vote_original %>%
  select(starts_with("v")) %>%
  prcomp() %>%
  .$x %>%
  as_tibble() %>%
  select(PC1, PC2)
vote_df <- bind_cols(vote_original, vote_pc)
clus_plot <- vote_df %>%
  ggplot(mapping = aes(x = PC1, y = PC2, color = state)) +
  geom_point()+
  transition_time(session) +
  labs(title = 'Session: {frame_time}', x = 'PC1', y = 'PC2') +
  ease_aes('linear')
animate(clus_plot, duration = 10, fps = 20, width = 400, height = 400, renderer = gifski_renderer())
anim_save("clust_gif.gif")
```

##Part 3

```{r stretch 3-a & b}
vote_113 <- vote %>%
  filter(session == 113) %>%
  select(starts_with("v"))

set.seed(20220414)
fviz_nbclust(vote_113,
             FUN = hcut,
             k.max = 10,
             method = "wss",
             hc_func = "hclust",
             hc_method = "ward.D2",
             hc_metric = "euclidean")

set.seed(20220414)
fviz_nbclust(vote_113,
             FUN = hcut,
             k.max = 10,
             method = "silhouette",
             hc_func = "hclust",
             hc_method = "ward.D2",
             hc_metric = "euclidean")
```


According to the results, it seems the optimal number of clusters based on both of the methods is 4.

```{r stretch 3c}
hclust_euc <- vote_113 %>%
  scale() %>%
  dist(method = "euclidean") %>%
  hclust(method = "ward.D2")
plot(hclust_euc, cex = 0.6, hang = -1)
rect.hclust(hclust_euc, k = 4, border = 2:5)
```

```{r stretch 3d}
vote_113_assign <- cutree(hclust_euc, k = 4)
vote_113_d <- bind_cols(vote_113, vote_113_assign)
#this is the final data frame generated
vote_113_d
```











